name: ExoBLAS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    # TODO: change @reusable-workflow to @main
    uses: exo-lang/ExoBLAS/.github/workflows/build-test.yml@reusable-workflow
    with:
      exo-ref: ${{ github.ref }}
      exo-blas-ref: main
