name: Gemmini CI
on:
  push:
    branches: [ 'master' ]
  pull_request:
jobs:
  gemmini:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/exo-lang/gemmini:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: exo-lang/gemmini-rocc-tests
          ref: exo
          submodules: recursive
          path: gemmini-rocc-tests

      - uses: actions/setup-python@v2

      - name: Generate code with Exo
        run: |
          python -m pip install -r requirements.txt
          pytest tests/gemmini/matmul/test_gemmini_matmul.py tests/gemmini/conv/test_gemmini_conv.py
        env:
          # TODO: fix the Gemmini harness
          RISCV: ""

      - name: Build GEMMINI tests
        run: ./build.sh
        env:
          # TODO: these need to be fixed rather than removed, but there are so many that the logs are not interpretable
          CFLAGS: -Wno-pointer-to-int-cast -Wno-discarded-qualifiers -Wno-int-to-pointer-cast -I ${{github.workspace}}/tests/gemmini/gemmini_build -I ${{github.workspace}}/src/exo/libs
        working-directory: gemmini-rocc-tests

      - name: Run GEMMINI tests
        run: |
          spike --extension=gemmini tiled_matmul_ws-baremetal
          spike --extension=gemmini tiled_matmul_ws-2-baremetal
          spike --extension=gemmini tiled_matmul_ws-3-baremetal
          spike --extension=gemmini tiled_matmul_ws-4-baremetal
          spike --extension=gemmini tiled_matmul_ws-5-baremetal
          spike --extension=gemmini tiled_matmul_ws-6-baremetal
          spike --extension=gemmini conv-baremetal
          spike --extension=gemmini conv-2-baremetal
          spike --extension=gemmini conv-3-baremetal
        working-directory: gemmini-rocc-tests/build/bareMetalC
