name: Gemmini CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  gemmini:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/exo-lang/gemmini:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y ninja-build
          python -m pip install -r requirements.txt
          python -m pip install -r dev-requirements.txt
          python -m pip install cmake build

      - name: Install exo
        run: |
          python -m build
          python -m pip install dist/*.whl

      - name: Configure GEMMINI tests
        shell: bash
        run : |
          cd /root/chipyard
          source $(conda info --base)/etc/profile.d/conda.sh
          source env.sh
          cd -
          cmake -G Ninja -S apps/gemmini -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --verbose
          cd build
          ctest -V
