name: Gemmini CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  gemmini:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/exo-lang/gemmini:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          apt-get remove -y cmake
          apt-get install -y ninja-build
          python -m pip install -r requirements.txt
          python -m pip install cmake build
          python -m build
          python -m pip install dist/*.whl

      - name: Build GEMMINI tests
        run: |
          cmake -G Ninja -S apps/gemmini -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Run GEMMINI tests
        run: ctest -V
        working-directory: build
