name: CI
on:
  push:
    branches: [ 'master' ]
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
        include:
          - runner: ubuntu-latest
            CC: clang-13
            CXX: clang++-13
            CLANG: clang-13
          - runner: macos-latest
            CC: clang # This will be system AppleClang
            CXX: clang++ # This will be system AppleClang
            CLANG: /usr/local/opt/llvm/bin/clang
    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}
      CLANG: ${{matrix.CLANG}}
    runs-on: ${{matrix.runner}}
    steps:
      - name: Checkout sources (including submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install tox==3.24.5

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@v3.21.2

      - name: Setup SDE binaries
        if: runner.os != 'macOS'
        uses: petarpetrovt/setup-sde@v2

      - name: Install Clang 13 (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 13

      - name: Install Clang 13 (macOS)
        if: runner.os == 'macOS'
        run: brew install llvm@13

      - name: Run tox
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  gemmini:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/exo-lang/gemmini:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: exo-lang/gemmini-rocc-tests
          ref: exo
          submodules: recursive
          path: gemmini-rocc-tests

      - uses: actions/setup-python@v2

      - name: Generate code with Exo
        run: |
          python -m pip install -r requirements.txt
          pytest tests/gemmini/matmul/test_gemmini_matmul.py tests/gemmini/conv/test_gemmini_conv.py

      - name: Build GEMMINI tests
        run: ./build.sh
        env:
          # TODO: these need to be fixed rather than removed, but there are so many that the logs are not interpretable
          CFLAGS: -Wno-pointer-to-int-cast -Wno-discarded-qualifiers -Wno-int-to-pointer-cast -I ${{github.workspace}}/tests/gemmini/gemmini_build -I ${{github.workspace}}/src/exo/libs
        working-directory: gemmini-rocc-tests

      - name: Run GEMMINI tests
        run: |
          spike --extension=gemmini tiled_matmul_ws-baremetal
          spike --extension=gemmini tiled_matmul_ws-2-baremetal
          spike --extension=gemmini tiled_matmul_ws-3-baremetal
          spike --extension=gemmini tiled_matmul_ws-4-baremetal
          spike --extension=gemmini tiled_matmul_ws-5-baremetal
          spike --extension=gemmini tiled_matmul_ws-6-baremetal
          spike --extension=gemmini conv-baremetal
          spike --extension=gemmini conv-2-baremetal
          spike --extension=gemmini conv-3-baremetal
        working-directory: gemmini-rocc-tests/build/bareMetalC
