name: CI
on:
  push:
    branches: [ 'master' ]
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
        include:
          - runner: ubuntu-latest
            CC: clang-15
            CXX: clang++-15
            CLANG: clang-15
          - runner: macos-latest
            CC: clang # This will be system AppleClang
            CXX: clang++ # This will be system AppleClang
            CLANG: /usr/local/opt/llvm/bin/clang
    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}
      CLANG: ${{matrix.CLANG}}
    runs-on: ${{matrix.runner}}
    steps:
      - name: Checkout sources (including submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install tox==3.24.5

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@v3.21.2

      - name: Setup SDE binaries
        if: runner.os != 'macOS'
        uses: petarpetrovt/setup-sde@v2

      - name: Install Clang 15 (Linux)
        if: runner.os == 'Linux'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15

      - name: Install Clang 15 (macOS)
        if: runner.os == 'macOS'
        run: brew install llvm@15

      - name: Run tox
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
