# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run.
on: [ push ]
# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  build:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
    # The type of runner that the job will run on
    runs-on: ${{matrix.runner}}
    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install -U pip wheel
      - run: pip install -r requirements.txt
      - run: python -m pytest
