name: CI
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
    runs-on: ${{matrix.runner}}
    steps:
      - name: Checkout sources (including submodules)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Setup SDE binaries
        uses: petarpetrovt/setup-sde@v1.2

      - name: Run PyTest
        run: python -m pytest

      - name: Run tox
        run: tox

      - name: Build package
        run: python -m build

      - name: Install package
        run: pip install dist/*.whl

      - name: Build apps with CMake
        run: |
          cmake -G Ninja -S apps -B build --preset gha-${{ runner.os }}
          cmake --build build

      - name: Check apps run with CMake
        run: ctest --output-on-failure
        working-directory: build
