name: Packaging
on:
  release:
    types: [ created ]
  push:
    branches: [ 'master' ]
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install setuptools wheel twine build

      - name: Build Python package
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Install Python package
        run: python -m pip install dist/*.whl

      - name: Test that exocc runs
        run: exocc -o tmp --stem conv apps/x86_demo/conv/conv.py

      - name: Show generated C code (manual inspection for now)
        run: cat tmp/conv.c

      # Will only run on release.
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
